### ISSUE TITLE
Accesso User Dashboard

### ISSUE THREAD

**Issue by edofiore** [zabealbe/KubeHosting#5]
Implementare la User Dashboard e la possibilità di accederci. Solo un utente registrato potrà accedere alla propria User Dashboard.

**Comment by UMR1352** [comment]
La dashboard deve essere generata dinamicamente partendo dalle informazioni dell'utente

- [ ] Creare la view della pagina con pug
- [ ] Predisporre una collezione sul DB per gestire i dati necessari alla dashboard (pacchetto attivo, numero di slot massime, lista dei servizi creati)
- [ ] Aggiungere una route
