### ISSUE TITLE
Visualizza catalogo

### ISSUE THREAD

**Issue by kevmoser** [zabealbe/KubeHosting#6]
Implementare una schermata con tutti i pacchetti disponibili

**Comment by UMR1352** [comment]
La schermata dei pacchetti deve essere generata dinamicamente (con un view engine) partendo da informazioni contenute nel DB. 

- [ ] Inserire i pacchetti disponibili in una collezione del DB
- [ ] Istruire il view engine (pug) su come generare la pagina partendo dai pacchetti disponibili
- [ ] Aggiungere la route

**Comment by UMR1352** [comment]
DONE
