### ISSUE TITLE
Creazione Servizio Utente

### ISSUE THREAD

**Issue by UMR1352** [zabealbe/KubeHosting#7]
Dalla propria dashboard un utente può aggiungere un nuovo servizio alla lista dei propri servizi. Un servizio è composto da:
- nome
- configurazione (dockerfile)
- in esecuzione / disattivo
- _(bisognerà sicuramente aggiungere altri campi specifici per Kubernetes)_

Per gestire i servizi occorrerà creare un API endpoint (`/service` potrebbe essere un buon nome). In questa issue ci occupiamo esclusivamente della creazione di servizi, pertanto il metodo che andiamo a gestire è `POST`.
- [ ] Aggiungere alla dashboard un form per la creazione di servizi
- [ ] Parsing & Sanitization dell'input
- [ ] Add the new service to the DB

**Comment by zabealbe** [comment]
La creazione di endpoint funzionanti prevede anche l'integrazione (anche parziale) con le APIs di kubernetes
